### ISSUE TITLE
Create unit tests

### ISSUE THREAD

**Issue by robertpenner** [jumpsuit/jumpstate#1]
If I find time to create unit tests for Jumpstate, my preferred stack would be mocha, chai, sinon. Sound good?

**Comment by tannerlinsley** [comment]
I would love to do it in Jest.  Have you looked into it at all?  It's
pretty legit.

**Comment by robertpenner** [comment]
Jest is new to me but fine; I'll let you set it up then.

**Comment by tannerlinsley** [comment]
I'll give it a try. I've never really done it either. ;)

**Comment by tannerlinsley** [comment]
@robertpenner I just pushed a Jest setup with the first test.  Should be pretty straightforward from here :)

**Comment by mheiber** [comment]
+1 for adding tests. I want to use Jumpstate, but can't recommend this to colleagues if the code is untested. Great work with this library, btw.

**Comment by tannerlinsley** [comment]
The testing framework is set up now. So feel free to pr some tests. Its not
a lot of code to test.
