### ISSUE TITLE
Script test wont run unit tests if there are lint errors

### ISSUE THREAD

**Issue by sirgallifrey** [jumpsuit/jumpstate#14]
When I run `yarn test` linter is executed but not unit tests. That happens because test:linter exits with code 1 and then npm-run-all exits too. I don't know it this is expected or not, but I expected that unit tests where executed independent of linting errors. This can be solved by placing a `-c` flag on npm-run-all command. I can PR that

**Comment by tannerlinsley** [comment]
Sounds good
