### ISSUE TITLE
Mixing with plain redux?

### ISSUE THREAD

**Issue by FoxxMD** [jumpsuit/jumpstate#43]
jumpstate is intriguing to me and seems like it could bring some huge benefits to a current project I am working on but it's not clear if it works well alongside regular redux. Can I mix and match normal redux usage (via `combineReducers`) with jumpstate reducers? What about actions, etc.?

**Comment by FoxxMD** [comment]
Awesome I will be giving this a try soon then 🎉  Thanks for the fast reply!

**Comment by tannerlinsley** [comment]
You bet!
